"""init dream, theme, and content_warning tables w/ relationships

Revision ID: 4ff0bf7c2a3a
Revises: 
Create Date: 2020-04-17 17:17:29.890209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff0bf7c2a3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_warning', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_warning_content_warning'), 'content_warning', ['content_warning'], unique=False)
    op.create_table('dream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Unicode(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_date'), 'dream', ['date'], unique=False)
    op.create_index(op.f('ix_dream_is_accepted'), 'dream', ['is_accepted'], unique=False)
    op.create_index(op.f('ix_dream_location'), 'dream', ['location'], unique=False)
    op.create_index(op.f('ix_dream_timestamp'), 'dream', ['timestamp'], unique=False)
    op.create_index(op.f('ix_dream_title'), 'dream', ['title'], unique=False)
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_theme'), 'theme', ['theme'], unique=False)
    op.create_table('content_warnings',
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('content_warning_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_warning_id'], ['content_warning.id'], ),
    sa.ForeignKeyConstraint(['dream_id'], ['dream.id'], ),
    sa.PrimaryKeyConstraint('dream_id', 'content_warning_id')
    )
    op.create_table('themes',
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dream.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('dream_id', 'theme_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    op.drop_table('content_warnings')
    op.drop_index(op.f('ix_theme_theme'), table_name='theme')
    op.drop_table('theme')
    op.drop_index(op.f('ix_dream_title'), table_name='dream')
    op.drop_index(op.f('ix_dream_timestamp'), table_name='dream')
    op.drop_index(op.f('ix_dream_location'), table_name='dream')
    op.drop_index(op.f('ix_dream_is_accepted'), table_name='dream')
    op.drop_index(op.f('ix_dream_date'), table_name='dream')
    op.drop_table('dream')
    op.drop_index(op.f('ix_content_warning_content_warning'), table_name='content_warning')
    op.drop_table('content_warning')
    # ### end Alembic commands ###
