"""create dream table


Revision ID: 635b1f7f10af
Revises: 
Create Date: 2020-04-17 15:27:27.496873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635b1f7f10af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('content', sa.Unicode(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_date'), 'dream', ['date'], unique=False)
    op.create_index(op.f('ix_dream_is_accepted'), 'dream', ['is_accepted'], unique=False)
    op.create_index(op.f('ix_dream_location'), 'dream', ['location'], unique=False)
    op.create_index(op.f('ix_dream_timestamp'), 'dream', ['timestamp'], unique=False)
    op.create_index(op.f('ix_dream_title'), 'dream', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dream_title'), table_name='dream')
    op.drop_index(op.f('ix_dream_timestamp'), table_name='dream')
    op.drop_index(op.f('ix_dream_location'), table_name='dream')
    op.drop_index(op.f('ix_dream_is_accepted'), table_name='dream')
    op.drop_index(op.f('ix_dream_date'), table_name='dream')
    op.drop_table('dream')
    # ### end Alembic commands ###
